name: Build EXE

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  upload-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache LLVM Installer
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: LLVM-21.1.6-win32.exe
          key: llvm-installer-21.1.6
      - name: Download LLVM Installer
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          curl -L -o LLVM-21.1.6-win32.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.6/LLVM-21.1.6-win32.exe
      - name: Install LLVM
        shell: pwsh
        run: |
          $p = Start-Process -FilePath ".\LLVM-21.1.6-win32.exe" -ArgumentList "/S" -PassThru
          $p.WaitForExit()
      - name: Run the tests
        shell: cmd
        run: |
          "C:\\Program Files (x86)\\LLVM\\bin\\clang" test.cc -fno-exceptions -D_CRT_SECURE_NO_WARNINGS -o test.exe && test.exe
      - name: Build EXE
        shell: cmd
        run: |
          build.bat

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pefile
          python postlink.py

      - name: Publish rolling release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest build
          files: persian-calendar.exe
